-- Watchlist table for user-saved tickers
create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  ticker text not null,
  created_at timestamptz not null default now(),
  constraint watchlist_user_ticker_unique unique (user_id, ticker),
  constraint watchlist_ticker_format check (ticker ~ '^[A-Z0-9.\-\^]{1,10}$')
);

create index if not exists watchlist_user_created_idx
  on public.watchlist (user_id, created_at desc);

alter table public.watchlist enable row level security;

-- Grant table-level privileges to authenticated users (required for session-bound clients)
grant select, insert, delete on public.watchlist to authenticated;

-- Allow users to read their own watchlist rows
create policy "watchlist_select_own"
  on public.watchlist
  for select
  using (auth.uid() = user_id);

-- Allow users to add their own watchlist rows
create policy "watchlist_insert_own"
  on public.watchlist
  for insert
  with check (auth.uid() = user_id);

-- Allow users to delete their own watchlist rows
create policy "watchlist_delete_own"
  on public.watchlist
  for delete
  using (auth.uid() = user_id);
